package pl.sdacademy.grabyourphoto.gallery.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "IMAGE".
 */
@Entity
public class Image {

    @Id(autoincrement = true)
    private Long id;
    private String resources;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 1590301345)
    public Image() {
    }

    public Image(Long id) {
        this.id = id;
    }

    @Generated(hash = 613252888)
    public Image(Long id, String resources) {
        this.id = id;
        this.resources = resources;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getResources() {
        return resources;
    }

    public void setResources(String resources) {
        this.resources = resources;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
